#!/bin/bash
vim=${vim:-vim}
case ${1:-base} in
  base)
    $vim -p bin/squatting lib/squatting.pl lib/Squatting.pm lib/Squatting/Controller.pm lib/Squatting/View.pm lib/Squatting/H.pm lib/Squatting/Mapper.pm
    ;;
  on)
    $vim -p lib/Squatting/On/*.pm
    ;;
  with)
    $vim -p lib/Squatting/With/AccessTrace.pm lib/Squatting/With/Log.pm
    ;;
esac
